# Generated by Django 3.0.5 on 2020-09-08 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=30, verbose_name='Сокращение')),
                ('full_name', models.CharField(max_length=100, verbose_name='Полное название')),
            ],
        ),
        migrations.CreateModel(
            name='LectureHall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schedule.Institute')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Название')),
                ('group', models.CharField(max_length=20, verbose_name='Группа')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='schedule.Institute')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('prefix', models.CharField(blank=True, max_length=100, null=True, verbose_name='Префикс')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schedule.Institute')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('лк', 'лк'), ('пр', 'пр'), ('лб', 'лб')], max_length=10, null=True, verbose_name='Тип')),
                ('position', models.IntegerField(verbose_name='Порядковый номер')),
                ('day', models.IntegerField(verbose_name='День недели')),
                ('is_even', models.NullBooleanField(verbose_name='Четный ли')),
                ('discipline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='schedule.Discipline')),
                ('lecture_hall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='schedule.LectureHall')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='schedule.Schedule')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='schedule.Teacher')),
            ],
        ),
        migrations.AddField(
            model_name='discipline',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schedule.Institute'),
        ),
    ]
