# Generated by Django 3.2.7 on 2021-09-24 19:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='Code')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=1024, verbose_name='Название')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='Code')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=1024, verbose_name='Имя')),
                ('education', models.CharField(max_length=1024, verbose_name='Образование')),
                ('experience', models.PositiveIntegerField(verbose_name='Опыт работы (мес.)')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('sex', models.CharField(choices=[('man', 'М'), ('female', 'Ж'), ('other', 'Другое')], max_length=1024, verbose_name='Пол')),
                ('family_status', models.CharField(max_length=1024, verbose_name='Семейное положение')),
                ('date_of_receipt', models.DateField(verbose_name='Дата приема')),
                ('date_of_dismissal', models.DateField(blank=True, null=True, verbose_name='Дата увольнения')),
                ('salary', models.PositiveIntegerField(verbose_name='Оклад')),
                ('reason_for_dismissal', models.TextField(blank=True, null=True, verbose_name='Причина увольнения')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='hr_analytics.company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
