# Generated by Django 3.2.7 on 2021-09-26 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_analytics', '0002_auto_20210925_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='post',
            field=models.CharField(default='-', max_length=1024, verbose_name='Должность'),
            preserve_default=False,
        ),
    ]
