# Generated by Django 3.0.5 on 2020-09-06 12:36

import chuvsu.utils
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, verbose_name='Код для индефикации')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('index', models.BooleanField(default=False, verbose_name='Домашний шаг')),
            ],
        ),
        migrations.CreateModel(
            name='VkUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30)),
                ('position', models.UUIDField(default=chuvsu.utils.home_code, verbose_name='Код текущего шага')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(default='{}', verbose_name='JSON данные')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quest_profile', to='chuvsu.VkUser')),
            ],
        ),
        migrations.CreateModel(
            name='ProxyStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Сообщение для перехода')),
                ('type', models.CharField(choices=[('jump', 'jump'), ('msg', 'msg'), ('quest', 'quest'), ('home', 'home')], max_length=10, verbose_name='Тип шага')),
                ('on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='on_proxy', to='chuvsu.ChatStep')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_proxy', to='chuvsu.ChatStep')),
            ],
        ),
        migrations.AddField(
            model_name='chatstep',
            name='actions',
            field=models.ManyToManyField(related_name='_chatstep_actions_+', through='chuvsu.ProxyStep', to='chuvsu.ChatStep'),
        ),
    ]
