# Generated by Django 3.1.7 on 2021-09-16 12:47

from django.db import migrations, models
import is_web.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='UUID4')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('header', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Заголовок')),
                ('title', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Название')),
                ('links', models.TextField(blank=True, null=True, verbose_name='Ссылки')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('img', models.ImageField(blank=True, null=True, upload_to=is_web.models.gen_card_img_path, verbose_name='Каринка')),
            ],
            options={
                'verbose_name': 'Пункт каталога',
                'verbose_name_plural': 'Пункты каталога',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='UUID4')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('header', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Заголовок')),
                ('title', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Название')),
                ('links', models.TextField(blank=True, null=True, verbose_name='Ссылки')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('img', models.ImageField(blank=True, null=True, upload_to=is_web.models.gen_card_img_path, verbose_name='Каринка')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
