# Generated by Django 3.1.7 on 2021-04-11 12:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='UUID4')),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Файл сабов')),
                ('translators_cache', models.JSONField(blank=True, null=True, verbose_name='Результаты от переводчиков')),
                ('parser', models.CharField(blank=True, max_length=100, null=True, verbose_name='Parser class name')),
                ('translators', models.JSONField(blank=True, null=True, verbose_name='List[str] of translators class name')),
                ('translators_params', models.JSONField(blank=True, null=True, verbose_name='Translators kwargs')),
                ('file_result', models.FileField(blank=True, null=True, upload_to='', verbose_name='Результат')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
