# Generated by Django 3.1.7 on 2021-04-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subtitle_translator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameLessFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=100, verbose_name='SHA256')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
