# Generated by Django 3.1.7 on 2021-04-30 09:10

from django.db import migrations, models
import subtitle_translator.models


class Migration(migrations.Migration):

    dependencies = [
        ('subtitle_translator', '0002_namelessfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleuser',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=subtitle_translator.models.gen_file_path, verbose_name='Файл сабов'),
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='file_result',
            field=models.FileField(blank=True, null=True, upload_to=subtitle_translator.models.gen_res_path, verbose_name='Результат'),
        ),
    ]
