# Generated by Django 3.1.7 on 2021-05-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atheneum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Название'),
        ),
    ]
