# Generated by Django 3.2.7 on 2021-09-26 01:10

import atheneum.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atheneum', '0002_page_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=atheneum.models.page_filename, verbose_name='Скан'),
        ),
    ]
