# Generated by Django 3.1.1 on 2020-09-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('old_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vkuser',
            name='user_id',
            field=models.IntegerField(unique=True, verbose_name='id пользователя'),
        ),
    ]
